.gitignore
.rubocop.yml
operations/check-csv/run.rb
operations/convert-to-utf8/run.rb

Closes https://github.com/PopulateTools/issues/issues/831
Autodetects the encoding before converting to UTF8. If it's already in UTF8, skips the conversion.

Fix utf8 conversion

---

Gemfile
Gemfile.lock
README.md
lib/gobierto_data/client.rb
lib/gobierto_etl_utils.rb
operations/check-csv/run.rb
operations/gobierto_data/upload-dataset/run.rb
operations/prepare-working-directory/run.rb

This PR adds new tasks to ETL utils:
- prepare working directory
- upload a dataset to gobierto data

Extract new tasks

---

operations/run-oracle-query/run.rb

Sets UTF8 to Oracle connection.
Tested in Getafe and working fine

Force env var to set UTF8 encoding

---

lib/gobierto_data/client.rb

Includes admin auth headers in gobierto data client get requests

Include admin auth header in get requests to API

---

operations/gobierto_data/extract-contracts/query.sql
operations/gobierto_data/extract-contracts/schema.json

This PR extracts number of proposals column to contracts table

Number of proposals

---

operations/gobierto_data/extract-contracts/query.sql
operations/gobierto_data/extract-tenders/query.sql

This PR closes https://github.com/PopulateTools/issues/issues/1193

Fix categories translations

---

operations/gobierto_data/extract-contracts/query.sql

This PR adds a different ID for minor contracts and for tenders with batches

Get a unique ID for contract batches

---

operations/gobierto_data/extract-contracts/query.sql

Related to #PopulateTools/open-licitaciones#683

Add gobierto_start_date to ETL query

---

operations/gobierto_data/extract-contracts/query.sql
operations/gobierto_data/extract-tenders/query.sql

Closes PopulateTools/Issues#1221

We start sending just the category key and let the client do the translation

---

operations/gobierto_data/extract-contracts/query.sql

Related to PopulateTools/gobierto#3773
Since we changed the keys, the value of the text in the CASE/WHEN has to change too.

Updating query to have i18n keys instead of plai ntext

---

operations/gobierto_data/extract-contracts/query.sql
operations/gobierto_data/extract-tenders/query.sql

This PR completes #106  and replaces the process_type in other parts of the query 🤦🏾

Replace new process_type key

---

pipelines/datasets/contratos/Jenkinsfile
pipelines/datasets/licitaciones/Jenkinsfile

add retry to pipelines:
- contratos
- licitaciones

1141 add retry to etl

---

operations/gobierto_data/extract-contracts/query.sql
operations/gobierto_data/extract-tenders/query.sql
pipelines/datasets/contratos/Jenkinsfile
pipelines/datasets/licitaciones/Jenkinsfile

Related to PopulateTools/issues#1337

Updates the SQL query for extracting tenders & contracts

---

operations/download/run.rb

This PR adds the ability to follow links if the response is a 30x

Follow link option

---

operations/gobierto_budgets/clear-budgets/run.rb

This PR updates the clear task to provided a list of types to remove the data from.

Clear results per type

---

lib/gobierto_data/client.rb
operations/gobierto_data/clone-dataset/run.rb

This PR makes the cloned dataset action to keep the existing name in case it exists.

Don't overwrite existing metadata

---

operations/load-csv-sqlite/run.rb

This PR accepts to provide the raw table name as argument.
This allows to load different tables in the same database to run transformations.

Accept a last argument with the raw table name

---

operations/excel-to-csv/run.rb

This PR adds a new operation to convert a Excel of a single sheet to a CSV.

Add Excel to CSV operation

---

Gemfile.lock
operations/excel-to-csv/run.rb

related with [#14 cars import dataset](https://github.com/PopulateTools/gobierto-etl-datos/pull/14)
This PR uses `roo` library to convert an excel file to csv file, and modifies previous version of excel to csv operation.

Excel to CSV operation

---

operations/download-csv-diff/run.rb

https://bugs.ruby-lang.org/issues/17391

Call File#exist? instead of File#exists?

---

Gemfile
Gemfile.lock
operations/gobierto_budgets/clear-budgets/run.rb
operations/gobierto_budgets/clear-previous-providers/run.rb

Related to https://github.com/PopulateTools/gobierto_budgets_data/pull/153
This should be merged together with https://github.com/PopulateTools/gobierto/pull/4230

Bump to new ElasticSearch

---

Gemfile
Gemfile.lock
operations/excel-to-csv/run.rb

Allow to transform old Excel files in `operations/excel-to-csv`

Handle Excel 2007
