operations/download/run.rb
* Increases `read_timeout` to 500 seconds (default is 60) because some ETL steps which includes downloads of resources from customers API are very slow
=> Increase read_timeout for download operation

lib/gobierto_data/client.rb, operations/gobierto_data/upload-dataset/run.rb
Adds support to `file_url` parameter to load data from a remote source. Example:
```
ruby $DEV_DIR/gobierto-etl-utils/operations/gobierto_data/upload-dataset/run.rb --api-token $API_TOKEN_ADMIN --gobierto-url http://madrid.gobierto.test --name "Calidad aire " --slug aire-getafe --table-name calidad_aire_getafe --file-url https://remote-gobierto-host/api/v1/data/data.csv?sql=select%20*%20from%20calidad_del_aire%20where%20estacion%20=%2014%20limit%2010
```
=> Accept file-url parameter to provide remote data

lib/gobierto_data/client.rb
This PR makes an action fail if the status code is different from 2xx. 
This is important because the Jenkins needs to detect the command has failed to stop the execution of the rest of the pipeline.
=> If the status code is not 2xx raise an error

README.md, lib/gobierto_etl_utils.rb, operations/prepare-working-directory/run.rb, operations/run-oracle-query/run.rb
Runs a query in Oracle using `sqlplus` utility.
Usage:
`$DEV_DIR/gobierto-etl-utils/operations/run-oracle-query/run.rb "CONNECTION STRING" input.sql $WORKING_DIR/output.csv`
Where:
- first argument: the connection string
- second argument: a file with the query to execute
- third argument: the output file (in CSV format)
=> New command run Oracle query

README.md, operations/api-download/run.rb
This PR adds an operation to download resources from endpoints allowing the inclusion of authentication headers in requests. After this addition the idea is to replace the current download operation with this in every ETL using it
=> Add api-download operation allowing authentication headers in requests

operations/api-download/run.rb
With this PR the api-download operation can be called:
```
ruby operations/api-download/run.rb --source-url source --output-file output --basic-auth username:password
```
=> Allow api-download operation to accept a basic_auth param

operations/gobierto_data/extract-contracts/query.sql, operations/gobierto_data/extract-contracts/schema.json
This PR adds tender columns open_proposals_date and submission_date to contracts dump in order to complete the Gobierto visualization of contracts (these attributes are being used in the contract info page)
=> Tender dates

operations/gobierto_data/extract-contracts/query.sql, operations/gobierto_data/extract-contracts/schema.json
This PR is part of https://github.com/PopulateTools/issues/issues/1182
Adds column estimated_value of tenders
=> Add estimated value column

operations/gobierto_data/extract-contracts/query.sql, operations/gobierto_data/extract-contracts/schema.json
This PR implements part of https://github.com/PopulateTools/issues/issues/1204
The award_date field calculation has been replaced by the plain award date, and a new field with the formalized date has been added
=> Extract award and formalized dates

operations/gobierto_data/extract-contracts/query.sql, operations/gobierto_data/extract-tenders/query.sql
If the category is null, we send the title and id of the "other" category.
=> Avoid sending null categories

operations/download-csv-diff/run.rb
Related to PopulateTools/gobierto-contratos#853
The gencat pipeline in gobierto-contratos should use this new script. 
This will download a csv file and store it with a timestamp. If there's a file with the previous day timestamp, it will make the diff of the two and that will be the output. Otherwise, the newest file will be the output.
A diff file between a csv from March 17th (one I had available in my computer) and one from today weights around 11MB. A full-size file is around 144MB, so this should be a big improvement.
=> Script to download csv and make diff if there's a previous version

pipelines/datasets/contratos/Jenkinsfile, pipelines/datasets/licitaciones/Jenkinsfile
This PR adds the pipeline to load contracts and tenders to this repo to avoid duplication across all the ETLs.
After this PR has been merged we could remove the tasks from the other ETLs and simplify a bit the setup of new visualizations too.
Notice the changes:
- the task won't load env vars from a .rben-vars file, env vars should be declared in the jenkins task
- the ine code var name has changed
- the read and write api token vars name has changed
=> Add contracts and tenders pipeline

operations/check-csv/run.rb
add new require condition csv should have more than 1 line.
```
curl http://dadesobertes.mataro.cat/factura_2anys.csv -o factura_2anys.csv -s
cd gobierto-etl-utils
ruby operations/convert-to-utf8/run.rb  ../factura_2anys.csv ../factura_2anys_uft8.csv
ruby operations/check-csv/run.rb ../factura_2anys_uft8.csv
head -n 0 ../factura_2anys_uft8.csv ../factura_2anys_uft8_empty.csv
ruby operations/check-csv/run.rb ../factura_2anys_uft8_empty.csv
head -n 1 ../factura_2anys_uft8.csv ../factura_2anys_uft8_headers.csv
ruby operations/check-csv/run.rb ../factura_2anys_uft8_headers.csv
```
=> 1141 modify check-csv to require csv more than 1 lines

pipelines/datasets/contratos/Jenkinsfile, pipelines/datasets/licitaciones/Jenkinsfile
This PR is related with https://github.com/PopulateTools/gobierto-etl-alcobendas/pull/6/files and https://github.com/PopulateTools/ansible-populate/pull/269/files
adds the option no-verify-ssl to fix imports for sites with custom certs, such as Alcobendas
=> Add no-verify-options for broken certs

Gemfile, Gemfile.lock, README.md, operations/gobierto_budgets/bubbles/run.rb, operations/gobierto_budgets/clear-budgets/run.rb, operations/gobierto_budgets/clear-previous-providers/run.rb, operations/gobierto_budgets/delete_total_budget/run.rb, operations/gobierto_budgets/import-executed-budgets/run.rb, operations/gobierto_budgets/import-invoices/run.rb, operations/gobierto_budgets/import-planned-budgets-updated/run.rb, operations/gobierto_budgets/import-planned-budgets/run.rb, operations/gobierto_budgets/update_total_budget/run.rb, operations/gobierto_budgets/xbrl/penloc/transform-planned/run.rb, operations/gobierto_budgets/xbrl/trimloc/transform-execution/run.rb, operations/gobierto_budgets/xbrl/trimloc/transform-planned-updated/run.rb, operations/gobierto_budgets/xbrl/trimloc/transform-planned/run.rb
Related to PopulateTools/issues#1352
This PR replaces namespaces of `GobiertoData` with `GobiertoBudgetsData` and updates the gems dependency to point `gobierto_budgets_data` instead of `gobierto_data`
=> 1352 rename gobierto data

operations/check-csv/run.rb
Related to gencat errors:
http://jenkins.populate.tools/job/gobierto-contratos%20import%20catalonia%20dataset%20(diff)/344/console
=> If the csv file has no lines, puts a warning message but allow execution.

operations/download-s3/run.rb, pipelines/budgets/update_trimloc_xbrl/Jenkinsfile
This PR moves the XBRL update budgets task from ETL Getafe to this generic repo.
It also lets to run it on any INE CODE, not just Getafe, so it can be used with new customers without having to run any change in Ansible or Jenkins.
=> Generic budgets update task

lib/gobierto_data/client.rb, operations/gobierto_data/clone-dataset/run.rb, pipelines/datasets/gobierto_data_dataset/Jenkinsfile
Closes #145 
This PR adds a new operation to create a dataset based on another Gobierto Data dataset.
This is very useful to extract a subset of rows of a Gobierto  dataset (i.e the rows of a municipality) and upload them to the municipality data portal.
=> Clone dataset operation

operations/extract-zip/run.rb
For [#1673 ](https://github.com/PopulateTools/issues/issues/1673)resolution, we need a new action for extracting zip contents.
Creates a new operation 'extract-zip' to extract content from a zip file.
Run the python script using: `ruby operations/extract-zip/run.rb documents/tmp/zipfile.zip`
=> extract zip operation

Gemfile, Gemfile.lock
In order to fix [ETL-UTILS/operations/excel-to-csv ](https://github.com/PopulateTools/gobierto-etl-utils/blob/master/operations/excel-to-csv/run.rb)I added gem `roo` to `Gemfile`.
=> Excel to csv / gem 'roo' - Gemfile

operations/check-csv/run.rb
This PR updates the check csv task to raise an error if the CSV checked is empty.
I'm not sure if some ETL's will start failing because of this change, but the expected dataset file should be a dataset with content.
=> Having no content raises an error

operations/gobierto_data/extract-contracts/query.sql
Related to PopulateTools/gobierto-contratos#3399
Launched the change [on staging](http://jenkins-staging.populate.tools/job/gobierto-etl-ribaroja%20contratos%20dataset/360/console). Riba Roja contracts on gobify has the correct dates now:
- https://ribaroja.gobify.net/visualizaciones/contratos/adjudicaciones/2197024
- https://ribaroja.gobify.net/visualizaciones/contratos/adjudicaciones/2196998
After merge, lauched the jenkins task of riba-roja contracts should fix the issue.
=> Changing priority for dates in contracts

operations/gobierto_budgets/official_xml/transform_executed/run.rb, operations/gobierto_budgets/official_xml/transform_planned/run.rb
This PR adds a couple of improvements in XML importing, for planned and executed budgets:
=> Improvements in XML import
